on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy_to_development:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    
    steps:
#       - name: Deploy to staging
#         uses: appleboy/ssh-action@master
#         with:
#           host: ec2-44-211-224-166.compute-1.amazonaws.com
#           username: ubuntu
#           key: ${{ secrets.SSH_PRI_KEY }}
#           script: |
#            whoami
#            pwd
#       - name: SSH into private server via bastion host
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SECRET_IP }}
#           username: ubuntu
#           key: ${{ secrets.SSH_PRI_KEY }}
#           bastion_host: ec2-44-211-224-166.compute-1.amazonaws.com
#           bastion_user: ubuntu
#           agent: yes
#           script: |
#             # Commands to execute on the private server
#             echo "Connected to the private server via the bastion host."
#             echo "Running commands on the private server..."
#             echo "Current directory:"
#             pwd
#             echo "List files:"
#             ls -l


#     - name: Install SSH client
#       run: sudo apt-get install openssh-client -y
      
      - name: executing remote ssh to bastion host
        env:
          MY_SECRET: ${{secrets.SSH_PRI_KEY}}
          SECRET_IP: ${{ secrets.SECRET_IP }} 
        shell: bash
        run: |
          pwd
          echo "$MY_SECRET" >> devops.pem && chmod 600 devops.pem
          ls
          eval `ssh-agent -s`
          ssh-add devops.pem
          ssh -A -tt ubuntu@ec2-44-211-224-166.compute-1.amazonaws.com -o "StrictHostKeyChecking=no"
          sudo ifconfig
          ssh ubuntu@10.0.0.39
          # ssh -i devops.pem -o "StrictHostKeyChecking=no" ubuntu@ec2-44-211-224-166.compute-1.amazonaws.com
          # sudo ifconfig
          # echo "connected!"
          # ssh -o "StrictHostKeyChecking=no" ubuntu@$SECRET_IP
          sudo ifconfig
          
