on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed

jobs:
  deploy_to_development:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install openssh-client -y
      
    - name: Add SSH private key
      run: echo $SSH_PRI_KEY > ssh_key.pem && chmod 600 ssh_key.pem
      
    - name: executing remote ssh to bastion host
      shell: bash
      run: |
        eval `ssh-agent -s`
        ssh-add ssh_key.pem
        ssh -J ubuntu@ec2-44-211-224-166.compute-1.amazonaws.com ubuntu@${{ secrets.SECRET_IP }}
        echo "connected!"
